### ISSUE TITLE
Unable to Install Aries Askar on Raspberry Pi 4

### ISSUE THREAD

**Issue by Swhite215** [hyperledger/aries-askar#126]
I get the following errors when trying to install aries-askar.

PI - Linux raspberrypi 6.1.19-v8+ #1637 SMP PREEMPT aarch64 GNU/Linux
Indexes - https://pypi.org/simple, https://www.piwheels.org/simple
Python Version - 3.10.7
pip3 - 21.2.4

Normal Install - `pip3 install aries-askar==0.2.7`

```
ERROR: Could not find a version that satisfies the requirement aries-askar==0.2.7 (from versions: 0.1.0, 0.1.2)
ERROR: No matching distribution found for aries-askar==0.2.7
```

Wheel Install - `pip3 install aries_askar-0.2.7-py3-none-manylinux2014_x86_64.wh`

```
ERROR: aries_askar-0.2.7-py3-none-manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

Askar Feature - `pip3 install aries-cloudagent[askar]==0.7.5`|

```
ERROR: Could not find a version that satisfies the requirement indy-credx~=0.3; extra == "askar" (from aries-cloudagent[askar]) (from versions: 0.2.1, 0.2.3)
ERROR: No matching distribution found for indy-credx~=0.3; extra == "askar"
```

**Comment by andrewwhitehead** [comment]
Version 0.2.8 will have a linux/aarch64 build, but for now you can install a pre-release: `aries_askar==0.2.8.dev4`

**Comment by Swhite215** [comment]
Still a failure when installing.

`pip3 install aries_askar==0.2.8.dev4`

```
ERROR: Could not find a version that satisfies the requirement aries_askar==0.2.8.dev4 (from versions: 0.1.0, 0.1.2)
ERROR: No matching distribution found for aries_askar==0.2.8.dev4

```
`pip3 install aries_askar-0.2.8.dev4-py3-none-manylinux2014_aarch64.whl`

```
ERROR: aries_askar-0.2.8.dev4-py3-none-manylinux2014_aarch64.whl is not a supported wheel on this platform.
```

**Comment by andrewwhitehead** [comment]
Could you try with `-v` or `-vvv` to see why it's not supported? Maybe it's a tagging issue. It installs fine in Linux on my M1.

**Comment by Swhite215** [comment]
`pip3 install -vvv --pre --index-url=https://pypi.org/project aries-askar==0.2.8.dev4`

```
Using pip 21.2.4 from /home/dev/.local/lib/python3.10/site-packages/pip (python 3.10)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-lju9k6f7
Created temporary directory: /tmp/pip-req-tracker-p7950bil
Initialized build tracking at /tmp/pip-req-tracker-p7950bil
Created build tracker: /tmp/pip-req-tracker-p7950bil
Entered build tracker: /tmp/pip-req-tracker-p7950bil
Created temporary directory: /tmp/pip-install-nlwbt_2s
Looking in indexes: https://pypi.org/project, https://www.piwheels.org/simple
2 location(s) to search for versions of aries-askar:
* https://pypi.org/project/aries-askar/
* https://www.piwheels.org/simple/aries-askar/
Fetching project page and analyzing links: https://pypi.org/project/aries-askar/
Getting page https://pypi.org/project/aries-askar/
Found index url https://pypi.org/project
Looking up "https://pypi.org/project/aries-askar/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /project/aries-askar/ HTTP/1.1" 304 0
  Skipping link: not a file: https://pypi.org/project/aries-askar/#content (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/help/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/sponsors/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/account/login/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/account/register/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/project/aries-askar/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/project/aries-askar/#description (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/project/aries-askar/#history (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/project/aries-askar/#files (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://github.com/hyperledger/aries-askar (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://libraries.io/pypi/aries-askar (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://packaging.python.org/guides/analyzing-pypi-package-downloads/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .org: mailto:aries@lists.hyperledger.org (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/user/cywolf/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/user/hyperledger/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/search/?c=License+%3A%3A+OSI+Approved+%3A%3A+Apache+Software+License (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/search/?c=License+%3A%3A+OSI+Approved+%3A%3A+MIT+License (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/search/?c=Operating+System+%3A%3A+OS+Independent (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3 (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/project/aries-askar/#data (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://github.com/hyperledger/indy-sdk (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://vonx.io (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .md: https://github.com/hyperledger/aries-askar/blob/master/CONTRIBUTING.md (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://developercertificate.org/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://github.com/apps/dco (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://github.com/hyperledger/aries-askar/blob/master/LICENSE-APACHE (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .0: http://www.apache.org/licenses/LICENSE-2.0 (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://github.com/hyperledger/aries-askar/blob/master/LICENSE-MIT (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: http://opensource.org/licenses/MIT (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/help/#project-release-notifications (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .xml: https://pypi.org/rss/project/aries-askar/releases.xml (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .dev4: https://pypi.org/project/aries-askar/0.2.8.dev4/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .dev1: https://pypi.org/project/aries-askar/0.2.8.dev1/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .7: https://pypi.org/project/aries-askar/0.2.7/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .6: https://pypi.org/project/aries-askar/0.2.6/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .5: https://pypi.org/project/aries-askar/0.2.5/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .4: https://pypi.org/project/aries-askar/0.2.4/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .3: https://pypi.org/project/aries-askar/0.2.3/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .2: https://pypi.org/project/aries-askar/0.2.2/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .1: https://pypi.org/project/aries-askar/0.2.1/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .0: https://pypi.org/project/aries-askar/0.2.0/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .0rc5: https://pypi.org/project/aries-askar/0.2.0rc5/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .0rc4: https://pypi.org/project/aries-askar/0.2.0rc4/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .0rc3: https://pypi.org/project/aries-askar/0.2.0rc3/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .0rc2: https://pypi.org/project/aries-askar/0.2.0rc2/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .3: https://pypi.org/project/aries-askar/0.1.3/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .2: https://pypi.org/project/aries-askar/0.1.2/ (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .0: https://pypi.org/project/aries-askar/0.1.0/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://packaging.python.org/installing/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives (from https://pypi.org/project/aries-askar/)
  Skipping link: none of the wheel's tags (py3-none-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/c4/b3/9b7201b52015212bf59cd7e56fbfa9328233b79e067537d4f8dbe71add39/aries_askar-0.2.7-py3-none-win_amd64.whl (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/project/aries-askar/#copy-hash-modal-4e760926-9224-4304-b551-f9db5462153d (from https://pypi.org/project/aries-askar/)
  Skipping link: none of the wheel's tags (py3-none-manylinux2014_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/9b/dc/b18f2c8d558d61056f5d365033e212e32fcf87eaf790099b01f8ebbc880e/aries_askar-0.2.7-py3-none-manylinux2014_x86_64.whl (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/project/aries-askar/#copy-hash-modal-ce6bfbcb-23a7-4746-b590-0131fd506b18 (from https://pypi.org/project/aries-askar/)
  Skipping link: none of the wheel's tags (py3-none-macosx_10_9_universal2) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/2d/8c/cd8b63392378fd084040604821022d9b472caf3c4727e7071af13f2d2482/aries_askar-0.2.7-py3-none-macosx_10_9_universal2.whl (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/project/aries-askar/#copy-hash-modal-69733c89-78c8-4d66-9fd4-5ee8811defa7 (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/project/aries-askar/#modal-close (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pip.pypa.io/en/stable/cli/pip_install/#hash-checking-mode (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://packaging.python.org/tutorials/packaging-projects/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://packaging.python.org/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://www.python.org/dev/peps/pep-0541/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://twitter.com/PyPI (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://dtdg.co/pypi (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/stats/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/trademarks/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/help/#feedback (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://github.com/pypi/warehouse (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://hosted.weblate.org/projects/pypa/warehouse/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://github.com/pypi/warehouse/graphs/contributors (from https://pypi.org/project/aries-askar/)
  Skipping link: unsupported archive format: .md: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/security/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://www.python.org/privacy/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/policy/terms-of-use/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/policy/acceptable-use-policy/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://status.python.org/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://donate.pypi.org (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://python.org/psf-landing (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://www.python.org/psf-landing/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://pypi.org/sitemap/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://aws.amazon.com/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://www.datadoghq.com/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://www.fastly.com/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://careers.google.com/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://www.python.org/psf/sponsors/#microsoft (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://www.pingdom.com/ (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://getsentry.com/for/python (from https://pypi.org/project/aries-askar/)
  Skipping link: not a file: https://statuspage.io (from https://pypi.org/project/aries-askar/)
Fetching project page and analyzing links: https://www.piwheels.org/simple/aries-askar/
Getting page https://www.piwheels.org/simple/aries-askar/
Found index url https://www.piwheels.org/simple
Looking up "https://www.piwheels.org/simple/aries-askar/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): www.piwheels.org:443
https://www.piwheels.org:443 "GET /simple/aries-askar/ HTTP/1.1" 200 291
Updating cache with response from "https://www.piwheels.org/simple/aries-askar/"
Caching due to etag
  Found link https://www.piwheels.org/simple/aries-askar/aries_askar-0.1.2-py3-none-any.whl#sha256=4a875918e9c47643185e992cb7df7c1447e5b15734f7df3531bc6d4322a6769b (from https://www.piwheels.org/simple/aries-askar/) (requires-python:>=3.6.3), version: 0.1.2
  Found link https://www.piwheels.org/simple/aries-askar/aries_askar-0.1.0-py3-none-any.whl#sha256=38b3d1683d85887f00b6d77eab631e1d21b071015a30f9979861e22e0f021e34 (from https://www.piwheels.org/simple/aries-askar/) (requires-python:>=3.6.3), version: 0.1.0
Skipping link: not a file: https://www.piwheels.org/simple/aries-askar/
Given no hashes to check 0 links for project 'aries-askar': discarding no candidates
ERROR: Could not find a version that satisfies the requirement aries-askar==0.2.8.dev4 (from versions: 0.1.0, 0.1.2)
ERROR: No matching distribution found for aries-askar==0.2.8.dev4
Exception information:
Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/dev/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('aries-askar==0.2.8.dev4')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/dev/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/dev/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 343, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('aries-askar==0.2.8.dev4'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/home/dev/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/home/dev/.local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/home/dev/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 103, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for aries-askar==0.2.8.dev4
WARNING: You are using pip version 21.2.4; however, version 23.0.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Removed build tracker: '/tmp/pip-req-tracker-p7950bil'
```

**Comment by andrewwhitehead** [comment]
Thanks, are you able to upgrade pip?

**Comment by andrewwhitehead** [comment]
Odd. On my machine with Docker I can run (roughly):

```
docker run --rm --platform linux/arm64 -ti ubuntu:latest
apt-get install --upgrade -y
apt-get install python3 python3-pip
pip install --upgrade pip
```

I get this successful install:

```
root@a01af3b99593:/# pip install aries_askar==0.2.8.dev4
Collecting aries_askar==0.2.8.dev4
  Downloading aries_askar-0.2.8.dev4-py3-none-manylinux2014_aarch64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 8.1 MB/s eta 0:00:00
Collecting cached-property~=1.5
  Downloading cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Installing collected packages: cached-property, aries_askar
Successfully installed aries_askar-0.2.8.dev4 cached-property-1.5.2
```

I notice it's mentioning the requires-python requirement, you could try `--ignore-requires-python`?

**Comment by andrewwhitehead** [comment]
How about `pip debug --verbose` to see the compatible tags? Mine has 496 on Python 3.10.6. Also do you have `wheel` installed?

**Comment by swcurran** [comment]
Any progress on this or can we close this issue?

**Comment by andrewwhitehead** [comment]
I believe we can close this based on https://github.com/hyperledger/indy-shared-rs/issues/41
