### ISSUE TITLE
aries_askar.error.AskarError: Resource handle in use

### ISSUE THREAD

**Issue by KimEbert42** [hyperledger/aries-askar#48]
Under load we've been encountering the following error

```
aries_askar.error.AskarError: Resource handle in use
Traceback (most recent call last):
  File "/cloudagent/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 457, in credential_exchange_list
    cred_ex_records = await V20CredExRecord.query(
  File "/cloudagent/aries_cloudagent/messaging/models/base_record.py", line 313, in query
    rows = await storage.find_all_records(
  File "/cloudagent/aries_cloudagent/storage/askar.py", line 189, in find_all_records
    for row in await self._session.handle.fetch_all(
  File "/usr/local/lib/python3.10/site-packages/aries_askar/store.py", line 436, in fetch_all
    await bindings.session_fetch_all(
  File "/usr/local/lib/python3.10/site-packages/aries_askar/bindings/__init__.py", line 237, in session_fetch_all
    return await invoke_async(
  File "/usr/local/lib/python3.10/site-packages/aries_askar/bindings/lib.py", line 354, in invoke_async
    return await self.loaded.invoke_async(
  File "/usr/local/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/usr/local/lib/python3.10/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError
```

I believe it is related to the following code in ffi/store.rs

```
    pub async fn borrow(&self, handle: K) -> Result<TryMutexGuard<V>, Error> {
        self.map
            .read()
            .await
            .get(&handle)
            .ok_or_else(|| err_msg!("Invalid resource handle"))?
            .1
            .try_lock_arc()
            .ok_or_else(|| err_msg!(Busy, "Resource handle in use"))
    }
```

Is there a reason to use try_lock_arc instead of lock_arc? It would seem to make more sense to wait to acquire the lock instead of failing the request? Or was this design decision because of a deadlocking scenario?

**Comment by andrewwhitehead** [comment]
I think the only reason it's not using lock_arc is because it was switched from another library recently, which didn't have that option. I've tested that change and it doesn't appear to have any impact on performance so I'll add a PR.
